CER2_AGUAYOMATIAS/urls.py
#Patrones para urlresolver
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proyectos.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
]

proyectos/urls.py
#Patrones para urlresolver
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('proyectos/', views.proyectos, name='proyectos'),
    path('proyecto/<int:proyecto_id>/', views.detalle_proyecto, name='detalle_proyecto'),
    path('crear/', views.crear_proyecto, name='crear_proyecto'),
    path('modificar/<int:proyecto_id>/', views.modificar_proyecto, name='modificar_proyecto'),
    path('patrocinar/<int:proyecto_id>/', views.patrocinar_proyecto, name='patrocinar_proyecto'),
]

proyectos/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    is_profesor = models.BooleanField(default=False)
    is_estudiante = models.BooleanField(default=False)

class Profesor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Estudiante(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Proyecto(models.Model):
    nombre_proyecto = models.CharField(max_length=100)
    estudiante = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    tema = models.CharField(max_length=100)
    nombre_profesor = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    patrocinado = models.BooleanField(default=False)  
    profesor_patrocinador = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='proyectos_patrocinados')  # Profesor que patrocina el proyecto

    def __str__(self):
        return self.nombre_proyecto

proyectos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Profesor, Estudiante, Proyecto

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('is_profesor', 'is_estudiante')

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = Profesor
        fields = '__all__'

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'
        

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = ['nombre_proyecto', 'tema', 'nombre_profesor', 'descripcion', 'patrocinado', 'profesor_patrocinador']  # Añadimos los nuevos campos

proyectos/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from .models import Proyecto
from .forms import ProyectoForm

def index(request):
    return render(request, 'index.html')

def proyectos(request):
    proyectos = Proyecto.objects.all()

    if request.user.is_authenticated and request.user.is_profesor:
        if 'filtrar_patrocinados' in request.GET:
            proyectos = proyectos.filter(patrocinado=True)
        elif 'filtrar_no_patrocinados' in request.GET:
            proyectos = proyectos.filter(patrocinado=False)

    return render(request, 'proyectos.html', {'proyectos': proyectos})

@login_required
def crear_proyecto(request):
    if request.method == 'POST':
        form = ProyectoForm(request.POST)
        if form.is_valid():
            proyecto = form.save(commit=False)
            proyecto.estudiante = request.user
            proyecto.save()
            return redirect('proyectos')
    else:
        form = ProyectoForm()
    return render(request, 'crear_proyecto.html', {'form': form})

@login_required
def modificar_proyecto(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    if request.user == proyecto.estudiante or request.user.is_profesor:
        if request.method == 'POST':
            form = ProyectoForm(request.POST, instance=proyecto)
            if form.is_valid():
                form.save()
                return redirect('proyectos')
        else:
            form = ProyectoForm(instance=proyecto)
        return render(request, 'modificar_proyecto.html', {'form': form})
    else:
        return redirect('proyectos')

@login_required
def detalle_proyecto(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    return render(request, 'detalle_proyecto.html', {'proyecto': proyecto})

@login_required
@user_passes_test(lambda u: u.is_profesor)
def patrocinar_proyecto(request, proyecto_id):
    proyecto = get_object_or_404(Proyecto, id=proyecto_id)
    proyecto.patrocinador = request.user
    proyecto.patrocinado = True
    proyecto.save()
    return redirect('proyectos')

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Portal de Iniciativas Estudiantiles{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="navbar-left">
                <img src="{% static 'src/Barra Colores.png' %}" alt="Barra Colores" class="logo">  <!-- Asegúrate de que la ruta sea correcta -->
                <span class="navbar-title">PIE USM SVM</span>
            </div>
            <ul>
                <li><a href="{% url 'index' %}">Inicio</a></li>
                <li><a href="{% url 'proyectos' %}">Proyectos</a></li>
                {% if user.is_authenticated %}
                    <li>
                        <form method="post" action="{% url 'logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" style="background: note; background-color: #074469; font-size: 1em; color: white; font-weight: bold;">
                                Cerrar Sesión ({{ user.username }})
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">Iniciar Sesión</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/crear_proyecto.html
{% extends 'base.html' %}

{% block title %}Crear Proyecto{% endblock %}

{% block content %}
<h2>Crear Proyecto</h2>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="id_nombre_proyecto">Nombre proyecto:</label>
            <input type="text" name="nombre_proyecto" maxlength="100" required id="id_nombre_proyecto" class="form-input">
        </p>
        <p>
            <label for="id_tema">Tema:</label>
            <input type="text" name="tema" maxlength="100" required id="id_tema" class="form-input">
        </p>
        <p>
            <label for="id_nombre_profesor">Nombre profesor:</label>
            <input type="text" name="nombre_profesor" maxlength="100" required id="id_nombre_profesor" class="form-input">
        </p>
        <p>
            <label for="id_descripcion">Descripción:</label>
            <textarea name="descripcion" cols="40" rows="10" required id="id_descripcion" class="form-textarea"></textarea>
        </p>
        <p>
            <label for="id_patrocinio">Patrocinio:</label>
            <input type="text" name="patrocinio" maxlength="100" id="id_patrocinio" class="form-input">
        </p>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
<style>
    .form-container {
        width: 50%;
        margin: 0 auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .form-container h2 {
        text-align: center;
        margin-bottom: 20px;
        font-family: 'Roboto', sans-serif;
    }

    .form-container form {
        display: flex;
        flex-direction: column;
    }

    .form-container form p {
        display: flex;
        flex-direction: column;
        margin-bottom: 15px;
    }

    .form-container form label {
        margin-bottom: 5px;
        font-family: 'Roboto', sans-serif;
    }

    .form-container form .form-input,
    .form-container form .form-textarea {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-family: 'Roboto', sans-serif;
        font-size: 1em;
    }

    .form-container form .form-input:focus,
    .form-container form .form-textarea:focus {
        outline: none;
        border-color: #005e90;
    }

    .form-container form .btn {
        align-self: center;
        padding: 10px 20px;
        background-color: #005e90;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1em;
        font-family: 'Roboto', sans-serif;
    }

    .form-container form .btn:hover {
        background-color: #004070;
    }
</style>
{% endblock %}

templates/detalle_proyecto.html
{% extends 'base.html' %}

{% block title %}Detalle del Proyecto{% endblock %}

{% block content %}
<div class="project-detail-container">
    <h2>{{ proyecto.nombre_proyecto }}</h2>
    <p><strong>Estudiante:</strong> {{ proyecto.estudiante.username }}</p>
    <p><strong>Tema:</strong> {{ proyecto.tema }}</p>
    <p><strong>Profesor:</strong> {{ proyecto.nombre_profesor }}</p>
    <p><strong>Descripción:</strong> {{ proyecto.descripcion }}</p>
    <p><strong>Patrocinado:</strong> {{ proyecto.patrocinado }}</p>
    <p><strong>Profesor Patrocinador:</strong> 
        {% if proyecto.profesor_patrocinador %}
            {{ proyecto.profesor_patrocinador.username }}
        {% else %}
            N/A
        {% endif %}
    </p>
    {% if user.is_authenticated %}
        {% if user == proyecto.estudiante or user.is_profesor %}
            <a href="{% url 'modificar_proyecto' proyecto.id %}" class="btn btn-primary">Editar</a>
        {% endif %}
    {% endif %}
</div>
<style>
    .project-detail-container {
        width: 50%;
        margin: 0 auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .project-detail-container h2 {
        text-align: center;
        margin-bottom: 20px;
        font-family: 'Roboto', sans-serif;
    }

    .project-detail-container p {
        margin-bottom: 10px;
        font-family: 'Roboto', sans-serif;
    }

    .project-detail-container .btn {
        display: block;
        width: fit-content;
        margin: 20px auto 0;
        padding: 10px 20px;
        background-color: #005e90;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1em;
        font-family: 'Roboto', sans-serif;
    }

    .project-detail-container .btn:hover {
        background-color: #004070;
    }
</style>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Portal de Iniciativas Estudiantiles{% endblock %}

{% block content %}
        <div class="banner">
            <div class="banner-content">
                <h1 class="title-large">Portal de Iniciativas Estudiantiles</h1>
                <h2 class="title-small">Universidad Santa María - Sede Viña del Mar</h2>
                <button class="initiativas" onclick="location.href='{% url 'proyectos' %}'">Ver Iniciativas</button>
            </div>
            <img src="{% static 'src/svm.jpg' %}" alt="SVM" class="central-image">
        </div>
    </header>
    {% endblock %}
</body>
</html>

templates/modificar_proyecto.html
{% extends 'base.html' %}

{% block title %}Modificar Proyecto{% endblock %}

{% block content %}
<h2>Modificar Proyecto</h2>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="id_nombre_proyecto">Nombre proyecto:</label>
            <input type="text" name="nombre_proyecto" maxlength="100" required id="id_nombre_proyecto" class="form-input">
        </p>
        <p>
            <label for="id_tema">Tema:</label>
            <input type="text" name="tema" maxlength="100" required id="id_tema" class="form-input">
        </p>
        <p>
            <label for="id_nombre_profesor">Nombre profesor:</label>
            <input type="text" name="nombre_profesor" maxlength="100" required id="id_nombre_profesor" class="form-input">
        </p>
        <p>
            <label for="id_descripcion">Descripción:</label>
            <textarea name="descripcion" cols="40" rows="10" required id="id_descripcion" class="form-textarea"></textarea>
        </p>
        <p>
            <label for="id_patrocinio">Patrocinio:</label>
            <input type="text" name="patrocinio" maxlength="100" id="id_patrocinio" class="form-input">
        </p>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
<style>
    .form-container {
        width: 50%;
        margin: 0 auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .form-container h2 {
        text-align: center;
        margin-bottom: 20px;
        font-family: 'Roboto', sans-serif;
    }

    .form-container form {
        display: flex;
        flex-direction: column;
    }

    .form-container form p {
        display: flex;
        flex-direction: column;
        margin-bottom: 15px;
    }

    .form-container form label {
        margin-bottom: 5px;
        font-family: 'Roboto', sans-serif;
    }

    .form-container form .form-input,
    .form-container form .form-textarea {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-family: 'Roboto', sans-serif;
        font-size: 1em;
    }

    .form-container form .form-input:focus,
    .form-container form .form-textarea:focus {
        outline: none;
        border-color: #005e90;
    }

    .form-container form .btn {
        align-self: center;
        padding: 10px 20px;
        background-color: #005e90;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1em;
        font-family: 'Roboto', sans-serif;
    }

    .form-container form .btn:hover {
        background-color: #004070;
    }
</style>
{% endblock %}

templates/proyectos.html
{% extends 'base.html' %}

{% block title %}Proyectos Presentados{% endblock %}

{% block content %}
<div class="portfolio-container">
    <h2 class="portfolio-title">Proyectos Presentados</h2>
    {% if user.is_authenticated %}
    <a href="{% url 'crear_proyecto' %}" class="initiativas create-btn">Crear Proyecto</a>
    {% endif %}

    <div class="filter-container">
        {% if user.is_profesor %}
            <a href="?filtrar_patrocinados=True" class="filter-btn">Patrocinados</a>
            <a href="?filtrar_no_patrocinados=True" class="filter-btn">No Patrocinados</a>
        {% endif %}
        <a href="{% url 'proyectos' %}" class="filter-btn">Todos los Temas</a>
    </div>

    <table class="projects-table">
        <thead>
            <tr>
                <th>Nombre Proyecto</th>
                <th>Estudiante</th>
                <th>Tema</th>
                <th>Profesor</th>
                <th>Patrocinado</th>
                <th>Profesor Patrocinador</th>
                <th>Ver Detalles</th>
                {% if user.is_authenticated %}
                <th>Editar</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for proyecto in proyectos %}
            <tr>
                <td>{{ proyecto.nombre_proyecto }}</td>
                <td>{{ proyecto.estudiante.username }}</td>
                <td>{{ proyecto.tema }}</td>
                <td>{{ proyecto.nombre_profesor }}</td>
                <td>{{ proyecto.patrocinado }}</td>
                <td>
                    {% if proyecto.profesor_patrocinador %}
                        {{ proyecto.profesor_patrocinador.username }}
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td><a href="{% url 'detalle_proyecto' proyecto.id %}" class="btn btn-primary">Ver Detalles</a></td>
                {% if user.is_authenticated %}
                    {% if user == proyecto.estudiante or user.is_profesor %}
                        <td><a href="{% url 'modificar_proyecto' proyecto.id %}" class="edit-btn">Editar</a></td>
                    {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}